#21 Added Altitude, Course, Speed and Accuracy
icapps/flutter-background-location-tracker pull request #42
Opened 2022-12-31 15:23 UTC by virtualmarc

Added additional informations to the `BackgroundLocationUpdateData` Object, including Altitude, Course, Speed and Accuracies.

2023-01-01 09:31 UTC, NicolaVerbeeck submitted a review, later dismissed
Thanks for your contribution

LGTM

2023-01-04 11:54 UTC, vanlooverenkoen requested changes

2023-01-04 11:54 UTC, vanlooverenkoen commented on test/src/model/background_location_update_data_test.dart
> +    const data = BackgroundLocationUpdateData(lat: 51.45, lon: 4.5, horizontalAccuracy: 1.2, alt: 42.3, verticalAccuracy: 0.3, course: 128.3, courseAccuracy: 14.3, speed: 12.2, speedAccuracy: 0.9);
formatting with `,`

2023-01-04 11:54 UTC, vanlooverenkoen commented on test/src/model/background_location_update_data_test.dart
> +    const data = BackgroundLocationUpdateData(lat: 51.45, lon: 4.5, horizontalAccuracy: 1.2, alt: 42.3, verticalAccuracy: 0.3, course: 128.3, courseAccuracy: 14.3, speed: 12.2, speedAccuracy: 0.9);
formatting with `,`

2023-01-04 11:55 UTC, vanlooverenkoen commented
I have requested now tokens on Travis. So normally with your next commit the builds will start again.

2023-01-04 12:14 UTC, vanlooverenkoen approved these changes

2023-01-11 15:06 UTC, merged

2023-01-11 15:25 UTC, vanlooverenkoen commented
v1.4.0 is released