Add start and stop methods to README
icapps/flutter-background-location-tracker pull request #59
Opened 2023-08-03 11:36 UTC by ashwin-dailype

Spent an entire day trying to figure out why the tracking never started for me. Then ran the example app to understand that
the button calls the startTracking method.

Felt that having the method in the README would really help everyone.

2023-08-07 20:12 UTC, ikbendewilliam commented
Good point! Thank you for the PR!

2023-08-07 20:12 UTC, ikbendewilliam approved these changes

2023-08-16 09:53 UTC, vanlooverenkoen requested changes

2023-08-16 09:53 UTC, vanlooverenkoen commented on README.md
> +startLocationTracking() async {
Future<void>

2023-08-16 09:53 UTC, vanlooverenkoen commented on README.md
> +stopLocationTracking() async {
Future<void>

2024-03-07 07:31 UTC, ikbendewilliam approved these changes

2024-03-07 07:31 UTC, merged